[package]
name = "wintab"
version = "0.1.0"
authors = ["Rasmus Halland <halland@gmail.com>"]
edition = "2018"

[dependencies]
winapi ={ version = "0.*", features = ["winuser", "winbase", "processthreadsapi", "errhandlingapi", "libloaderapi", "psapi"] }

